#! /bin/bash

# Installing Chrome Remote Desktop
sudo apt update
sudo apt-get install wget curl -y

wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb

sudo apt update
sudo dpkg --install chrome-remote-desktop_current_amd64.deb
sudo apt install --assume-yes --fix-broken

# install an X Window System desktop environment and window manager
sudo DEBIAN_FRONTEND=noninteractive \
    apt install --assume-yes xfce4 desktop-base

sudo bash -c 'echo "exec /etc/X11/Xsession /usr/bin/xfce4-session" > /etc/chrome-remote-desktop-session'
sudo apt install --assume-yes xscreensaver
sudo apt install --assume-yes task-xfce-desktop

# Disable the display manager service
sudo systemctl disable lightdm.service

# install the Chrome browser on your instance
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

sudo dpkg --install google-chrome-stable_current_amd64.deb
sudo apt install --assume-yes --fix-broken
